_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": linux-x86_64
epochs:
    value: 10
learning_rate:
    value: 0.01
